// $[EUSART_SL_IOSTREAM_EUSART_EUSART1]
#ifndef SL_IOSTREAM_EUSART_EUSART1_PERIPHERAL   
#define SL_IOSTREAM_EUSART_EUSART1_PERIPHERAL    EUSART1
#endif
#ifndef SL_IOSTREAM_EUSART_EUSART1_PERIPHERAL_NO
#define SL_IOSTREAM_EUSART_EUSART1_PERIPHERAL_NO 1
#endif




// [EUSART_SL_IOSTREAM_EUSART_EUSART1]$


