M48
; DRILL file KiCad 10.0.0 date 2026-07-15T14:57:41
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-15T14:57:41-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X103.46Y-77.5
X108.54Y-76.484
X108.54Y-78.516
T2
X87.5Y-52.5
X87.5Y-77.5
X112.5Y-52.5
X112.5Y-77.5
M30
